---
AWSTemplateFormatVersion: 2010-09-09


Description: >
  This template deploys the base infra for PN
Parameters:
  EnvName:
    Type: String
    Description: Nome dell'ambiente destinazione
  EnvNumber:
    Type: String
    Description: Second byte from the left for VPC CIDR
  TemplateBucket:
    Type: String
    Default: pagopa-pn-infra-common-template
    Description: >
      The S3 bucket from which to fetch the templates used by this stack.

Resources:
  ### VPC ###
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.eu-west-1.amazonaws.com/${TemplateBucket}/templates/vpc.yaml"
      Parameters:
        EnvName: !Ref EnvName
        EnvNumber: !Ref EnvNumber

  VPCEndpoints:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.eu-west-1.amazonaws.com/${TemplateBucket}/templates/vpc_endpoints.yaml"
      Parameters:
        EnvName: !Ref EnvName
        EnvNumber: !Ref EnvNumber
        Subnets:
          Fn::Join:
            - ","
            - - !GetAtt VPC.Outputs.PublicSubnet1Id
              - !GetAtt VPC.Outputs.PublicSubnet2Id
        RouteTableIds:
          Fn::Join:
            - ","
            - - !GetAtt VPC.Outputs.PublicRouteTable1
              - !GetAtt VPC.Outputs.PublicRouteTable2
        VpcId: !GetAtt VPC.Outputs.VpcId

  ### ECS ###
  ECSCluster:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.eu-west-1.amazonaws.com/${TemplateBucket}/templates/ecs_cluster.yaml"
      Parameters:
        EnvName: !Ref EnvName


  ### SQS ###
  DeliveryPushInputsQueue:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.eu-west-1.amazonaws.com/${TemplateBucket}/templates/sqs.yaml"
      Parameters:
        QueueName: !Sub '${EnvName}-delivery_push_inputs'
        DelaySeconds: 1
        MessageRetentionPeriod: 36000 # 10h
        DeadLetterQueueName: !Sub '${EnvName}-delivery_push_inputs-dlq'

  DeliveryPushActionsQueue:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.eu-west-1.amazonaws.com/${TemplateBucket}/templates/sqs.yaml"
      Parameters:
        QueueName: !Sub '${EnvName}-delivery_push_actions'
        DelaySeconds: 1
        MessageRetentionPeriod: 36000 # 10h
        DeadLetterQueueName: !Sub '${EnvName}-delivery_push_actions-dlq'

  ExternalChannelsInputsQueue:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.eu-west-1.amazonaws.com/${TemplateBucket}/templates/sqs.yaml"
      Parameters:
        QueueName: !Sub '${EnvName}-external_channel_inputs'
        DelaySeconds: 1
        MessageRetentionPeriod: 36000 # 10h
        DeadLetterQueueName: !Sub '${EnvName}-external_channel_inputs-dlq'

  ExternalChannelsOutputsQueue:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.eu-west-1.amazonaws.com/${TemplateBucket}/templates/sqs.yaml"
      Parameters:
        QueueName: !Sub '${EnvName}-external_channel_outputs'
        DelaySeconds: 1
        MessageRetentionPeriod: 36000 # 10h
        DeadLetterQueueName: !Sub '${EnvName}-external_channel_outputs-dlq'

  ExternalChannelsElabResQueue:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.eu-west-1.amazonaws.com/${TemplateBucket}/templates/sqs.yaml"
      Parameters:
        QueueName: !Sub '${EnvName}-external_channel_elab_res'
        DelaySeconds: 1
        MessageRetentionPeriod: 36000 # 10h
        DeadLetterQueueName: !Sub '${EnvName}-external_channel_elab_res-dlq'

  DeliveryPushActionsDoneQueue:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.eu-west-1.amazonaws.com/${TemplateBucket}/templates/sqs.yaml"
      Parameters:
        QueueName: !Sub '${EnvName}-delivery_push_actions-done'
        DelaySeconds: 2
        MessageRetentionPeriod: 36000 # 10h
        DeadLetterQueueName: !Sub '${EnvName}-delivery_push_actions-done-dlq'
