---
AWSTemplateFormatVersion: 2010-09-09


Description: >
  This template deploys the base infra for PN
Parameters:
  EnvName:
    Type: String
    Description: Nome dell'ambiente destinazione
  EnvNumber:
    Type: String
    Description: Second byte from the left for VPC CIDR
  TemplateBucket:
    Type: String
    Default: pagopa-pn-infra-common-template
    Description: >
      The S3 bucket from which to fetch the templates used by this stack.

Resources:
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.eu-west-1.amazonaws.com/${TemplateBucket}/templates/vpc.yaml"
      Parameters:
        EnvName: !Ref EnvName
        EnvNumber: !Ref EnvNumber


  VPCEndpoints:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.eu-west-1.amazonaws.com/${TemplateBucket}/templates/vpc_endpoints.yaml"
      Parameters:
        EnvName: !Ref EnvName
        EnvNumber: !Ref EnvNumber
        Subnets:
          Fn::Join:
            - ","
            - - !GetAtt VPC.Outputs.PublicSubnet1Id
              - !GetAtt VPC.Outputs.PublicSubnet2Id
        RouteTableIds:
          Fn::Join:
            - ","
            - - !GetAtt VPC.Outputs.PublicRouteTable1
              - !GetAtt VPC.Outputs.PublicRouteTable2
        VpcId: !GetAtt VPC.Outputs.VpcId


  ECSCluster:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.eu-west-1.amazonaws.com/${TemplateBucket}/templates/ecs_cluster.yaml"
      Parameters:
        EnvName: !Ref EnvName
